---

- name: get current setting from xml for multivalue alias
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid='{{ item.0.uuid }}']/{{ item.1.key }}"
    content: text
  register: _configured_multivalue_alias
  ignore_errors: true  # do not fail if node not exists

- name: check if multivalue list is sortable
  ansible.builtin.set_fact:
    _listsort: "{{ item.1.list | sort }}"
  ignore_errors: true
  register: _listsortresult

- name: fix multivalue list for sorting
  ansible.builtin.set_fact:
    _listsort: "[{% for i in item.1.list %}'{{ i }}',{% endfor %}]"
  when: _listsortresult.failed | bool

- name: set multivalue alias
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid='{{ item.0.uuid }}']/{{ item.1.key }}"
    value: "{{ _listsort | join('\n') }}"
    pretty_print: true
  notify: reconfigure aliases
  when:
    - _configured_multivalue_alias.failed | bool or _configured_multivalue_alias.matches[0][item.1.key].split('\n') | sort != _listsort | sort

...
