---

# examples
#
# some notes regarding uuid
# see https://github.com/naturalis/ansible-opnsense/issues/61
#
# opn_alias:
#   - uuid: b9ca4f72-ab35-5c48-8460-d71a7ef50184
#     settings:
#       - key: name
#         value: PRIVATE_NETWORKS
#       - key: type
#         value: network
#       - key: content
#         list:
#           - 10.0.0.0/8
#           - 172.16.0.0/12
#           - 192.168.0.0/16
#       - key: enabled
#         value: 1
#       - key: description
#         value: "opn alias PRIVATE_NETWORKS"
#   - uuid: 67b86e3a-0534-5e15-86f7-eea1116dc9be
#     settings:
#       - key: name
#         value: FIREWALL_ADMIN_ACCESS_PORTS_tcp
#       - key: type
#         value: port
#       - key: content
#         list:
#           - 22
#           - 443
#       - key: enabled
#         value: 1
#       - key: description
#         value: "admin access ports to the firewall"
#   - uuid: e804a2e9-f765-58cc-a6d6-caa43be7ceef
#     settings:
#       - key: name
#         value: BLOCKLIST_SPAMHAUS_DROP
#       - key: type
#         value: urltable
#       - key: content
#         value: "https://www.spamhaus.org/drop/drop.txt"
#       - key: enabled
#         value: 1
#       - key: description
#         value: "Spamhaus DROP list"
#       - key: updatefreq
#         value: 0.041666666666666664

- name: aliases
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid='{{ item.0.uuid }}']/{{ item.1.key }}"
    value: "{{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
  when: item.1.value is defined

- name: multivalue aliases
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid='{{ item.0.uuid }}']/{{ item.1.key }}"
    value: "{{ item.1.list | join('\n') }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
  when: item.1.list is defined

# valid types can be determined from
# https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.xml
- name: test aliases
  ansible.builtin.fail:
    msg: "alias with the uuid '{{ item.0.uuid }}' has wrong type '{{ item.1.value }}'"
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
  when:
    - opn_check_alias | default(true) | bool
    - item.1.key == "type"
    - item.1.value is not in ['host', 'network', 'port', 'url', 'urltable', 'geoip', 'networkgroup', 'mac', 'asn', 'dynipv6host', 'authgroup', 'internal', 'external']  # noqa yaml[line-length]

...
