---

# example
# opn_filter:
#   - descr: icmp allow
#     uuid: ... # uuid definition is optional but recommended
#     settings:
#       - key: type
#         value: pass
#       - key: ipprotocol
#         value: inet
#       - key: statetype
#         value: keep state
#       - key: direction
#         value: any
#       - key: quick
#         value: '1'
#       - key: category
#         value: TEST
#       - key: floating
#         value: 'yes'
#       - key: protocol
#         value: icmp
#       - key: source/any
#         value: '1'
#       - key: destination/any
#         value: '1'
# if uuid is not defined, the description is used to identify rules

- name: process filter ...
  ansible.builtin.include_tasks: filterdo.yml
  with_items:
    - "{{ opn_filter | default([]) + opn_vlan_filter | default([]) }}"
  loop_control:
    label: "{{ _filter.descr | default(_filter.uuid) }}"
    loop_var: _filter

...
