---

- name: process filter ...
  ansible.builtin.include_tasks: filterdo.yml
  with_items:
    - "{{ opn_filter | default([]) + opn_vlan_filter | default([]) }}"
  loop_control:
    label: "{{ _filter.descr }}"
    loop_var: _filter

...
