---

- name: filter with uuid
  ansible.builtin.include_tasks: filterdouuid.yml
  when: _filter.uuid is defined

- name: filter without uuid
  ansible.builtin.include_tasks: filterdolegacy.yml
  when: _filter.uuid is not defined

# check if in one rule for dest and src only one of address, network or any is defined
- name: "check filter rule '{{ _filter.descr | default(_filter.uuid) }}' for errors in source or destination"
  ansible.builtin.include_tasks: filtertest.yml
  when: opn_check_filter_rules | default(true) | bool
  with_items:
    - source
    - destination
  loop_control:
    label: "{{ _filter.descr | default(_filter.uuid) }} {{ _srcdst }}"
    loop_var: _srcdst

...
