---

# definition:
# opn_group:
#   - name: g2
#     settings:
#       - key: gid
#         value: 2001
#       - key: description
#         value: group two
#       - key: member
#         value: 2000
#       - key: member
#         value: 2001

- name: groups - create
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/system/group[name/text()='{{ item.0.name }}']/{{ item.1.key }}"
    value: "{{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_group }}"
    - settings
  when:
    - opn_group is defined
    - item.1.key is defined
    - not item.1.key == "member"

- name: groups - members
  ansible.builtin.include_tasks: groupmembers.yml
  with_items:
    - "{{ opn_group }}"
  loop_control:
    loop_var: group
    label: "{{ group.name }}"
  when: opn_group is defined

...
