---
# example:
# opn_staticroutes:
#   - descr: route to nowhere
#     uuid: 6293069e-251e-5dbd-8594-60035417f2c8
#     settings:
#       - key: network
#         value: 100.64.0.0/10
#       - key: gateway
#         value: GW2NOWHERE  # must be defined in opn_gateways
#       - key: enabled  # since CE 26.1.11 / BE 26.4.2
#         value: 1
#

- name: ensure required facts are available
  ansible.builtin.fail:
    msg: opnsense staticroutes requires role ansible-opnsense-facts
  when:
    - opn_staticroutes is defined and opn_staticroutes
    - ansible_local.opnsense.core.product_version is not defined

- name: staticroutes check for deprecated disabled key
  ansible.builtin.assert:
    that:
      - not item.1.key == 'disabled'
    fail_msg: "opn_staticroutes : {{ item.1.key }} key is deprecated for {{ ansible_local.opnsense.core.product_version }}"
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings
  when:
    - ansible_local.opnsense.core.product_version is version_compare('26.1.11', '>=')

- name: staticroutes
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']/{{ item.1.key }}"
    value: "{{ (item.1.value == None) | ternary(item.1.value, (item.1.value | string)) }}"
    pretty_print: true
  notify: configure routing
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings

- name: route attribute uuid
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']"
    attribute: uuid
    value: "{{ item.0.uuid }}"
    pretty_print: true
  notify: configure routing
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings
...
