---
- name: staticroutes
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']/{{ item.1.key }}"
    value: "{{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings

- name: route attribute uuid
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']"
    attribute: uuid
    value: "{{ item.0.uuid }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings
...
