---

# remote path of the config
config_path: /conf/config.xml

# local path for the config
local_config_path: /tmp/config-{{ inventory_hostname }}.xml

# set this to true in order to adjust the encoding of the xml before uploading it
# recommendet to set this to true!
# requires php-cli and php-xml to be installed on the ansible runner
opn_fix_xml_encoding: false

# list of keys per task to sort values
opn_sort_values:
  filter:
    - interface

# unset handlers: regex to match in opn_unset -> handler to call
opn_unset_handlers:
  '^ipsec$': 'stop ipsec'
  '^system/user': 'local user sync'
  '^ca': 'trust configure'
  '^cert': 'trust configure'

# default values for opn_openvpn_instances
opn_openvpn_instances_defaults:
  enabled: 1
  dev_type: tun
  verb: 3
  proto: udp
  topology: subnet
  role: server
  register_dns: 0
  verify_client_cert: require
  use_ocsp: 0
  username_as_common_name: 0
  strictusercn: 0

# defaults for opn_openvpn_overwrites
opn_openvpn_overwrites_defaults:
  enabled: 1
  block: 0
  push_reset: 0
  register_dns: 0

opn_unboundplus_uuid_sections:
  dots: dot
  hosts: host
  aliases: alias
  # domains: domains / domain is gone in favor of dots : see #111
  acls: acl

# defaults for some elements
opn_unboundplus_uuid_sections_defaults:
  dots:
    dot:
      enabled: 1
      type: forward
      port:
      verify:
      forward_tcp_upstream: 0
      description:

opn_cron_jobs_defaults:
  origin: cron
  enabled: 1
  minutes: 0
  hours: 0
  days: '*'
  months: '*'
  weekdays: '*'
  who: root
  parameters:

# Swanctl section name -> list section name
opn_Swanctl_sections:
  Connections: Connection
  locals: local
  remotes: remote
  children: child
  Pools: Pool
  VTIs: VTI
  SPDs: SPD
# IPsec section name -> list section name
opn_IPsec_sections:
  keyPairs: keyPair
  preSharedKeys: preSharedKey
# Swanctl defaults
opn_Swanctl_defaults:
  Connections:
    Connection:
      enabled: 1
      proposals: default
      unique: 'no'
      aggressive: 0
      version: 0
      mobike: 1
      local_addrs:
      local_port: # 500 is default if empty
      remote_addrs:
      remote_port: # 500 is default if empty
      encap: 0
      reauth_time:
      rekey_time:
      over_time:
      dpd_delay:
      dpd_timeout:
      pools:
      send_certreq: 1
      send_cert:
      keyingtries:
      description:
  locals:
    local:
      enabled: 1
  remotes:
    remote:
      enabled: 1
  children:
    child:
      enabled: 1
  Pools:
    Pool:
      enabled: 1
      name:
      addrs:
      dns:
  VTIs:
    VTI:
      enabled: 1
      reqid:
      local:
      remote:
      tunnel_local:
      tunnel_remote:
      tunnel_local2:
      tunnel_remote2:
      description:
  SPDs:
    SPD:
      enabled: 1
      protocol: esp
      reqid:
      connection_child:
      source:
      destination:
      description:
# IPsec defaults
opn_IPsec_defaults:
  preSharedKeys:
    preSharedKey:
      ident:
      remote_ident:
      keyType: PSK
      Key:
      description:

#######################
# sync user from ldap #
#######################
# set this to true in order to enable the sync
opn_sync_users_from_ldap: false

# remove all users with scope=user that are not present in the ldap sync
opn_sync_users_from_ldap_remove_vanished: false

# ldap settings
opn_sync_users_ldap_url: ldaps://dc.example.org
opn_sync_users_ldap_scope: sub  # one|sub|base
opn_sync_users_ldap_basedn: OU=Users,...

# ldap auth params
opn_sync_users_ldap_auth: []
# example opn_sync_users_ldap_auth
# opn_sync_users_ldap_auth:
#  - --user=ldapaccount
#  - --workgroup=WGP
#  - --password={{ ldappw }}
# and define the ldappw vaulted
# ldappw: !vault | ...

# additional args for ldbsearch
opn_sync_users_ldap_args:
  - '--show-binary'
  - '--sorted'

# ldap fields to fetch and map to opn user
# map of opnsense user field -> ldap field
opn_sync_users_ldap_fields:
  name: sAMAccountName
  descr: cn
  email: mail
# uuid: objectGUID
# otp_seed: anotherLdapAttribute

# map of opnsense user field -> map of reges search -> replace to manipulate the value
opn_sync_users_ldap_fields_jinja2regexreplace: {}
# example
# opn_sync_users_ldap_fields_jinja2regexreplace:
#   otp_seed:
#     '#@[-+_.a-zA-Z0-9]*=': ''
#     '&.*': ''
# this will be evaluated to the equivalent of:
# ... | regex_replace('#@[-+_.a-zA-Z0-9]*=', '') | regex_replace('&.*', '')

# ldap filter
# userAccountControl: see https://learn.microsoft.com/troubleshoot/windows-server/active-directory/useraccountcontrol-manipulate-account-properties
#   512:  NORMAL_ACCOUNT
#   2:    ACCOUNTDISABLE
#   32:   PASSWD_NOTREQD
opn_sync_users_ldap_filter: '(&(objectCategory=organizationalPerson)(objectClass=User)(userAccountControl:1.2.840.113556.1.4.803:=512)(!(|(userAccountControl:1.2.840.113556.1.4.803:=2)(userAccountControl:1.2.840.113556.1.4.803:=32))))'  # noqa yaml[line-length]

...
