---

# some configctl infos
# https://docs.opnsense.org/manual/settingsmenu.html

# alias handlers
# see: src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php

# api endpoint /api/firewall/alias/reconfigure

# NOTE: all configured handlers must be defined as dummy handler in test/test.yml too

# alias
# -----

- name: template reload OPNsense/Filter  # noqa no-changed-when
  ansible.builtin.command: configctl template reload OPNsense/Filter
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter reload skip_alias  # noqa no-changed-when
  ansible.builtin.command: configctl filter reload skip_alias
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter refresh_aliases  # noqa no-changed-when
  ansible.builtin.command: configctl filter refresh_aliases
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

# filter
# -----

- name: reconfigure filter  # noqa no-handler no-changed-when
  ansible.builtin.command: "{{ item }}"
  throttle: 1
  # TODO: determine if both methods are required / order / if one is sufficient/better
  #       maybe use some common handlers for alias/filter
  with_items:
    - configctl filter reload
    - configctl filter sync
  when:
    - config is defined
    - config.changed | bool

# dnsservers
# ----------

- name: reconfig dnsservers  # noqa no-changed-when
  ansible.builtin.command: /usr/local/sbin/opnsense_service_mimic.php system_resolver_configure
  listen:
    - reconfigure dnsservers
  when:
    - config is defined
    - config.changed | bool

# dhcp
# ----

- name: reconfig dhcpd service  # noqa no-changed-when
  ansible.builtin.command: /usr/local/sbin/opnsense_service_mimic.php reconfigure_dhcpd
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

- name: restart dhcpd service  # noqa no-changed-when
  ansible.builtin.command: configctl dhcpd restart
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

# wireguard
# ---------

# this will fail if the package is not installed
- name: reconfig wireguard  # noqa no-changed-when
  ansible.builtin.command: configctl wireguard configure
  listen:
    - restart wireguard
  when:
    - config is defined
    - config.changed | bool

# this will fail if the package is not installed
- name: restart wireguard  # noqa no-changed-when
  ansible.builtin.command: configctl wireguard restart
  listen:
    - restart wireguard
  when:
    - config is defined
    - config.changed | bool
