---

# some configctl infos
# https://docs.opnsense.org/manual/settingsmenu.html

# alias handlers
# see: src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php

# api endpoint /api/firewall/alias/reconfigure

- name: template reload OPNsense/Filter  # noqa no-changed-when
  ansible.builtin.command: configctl template reload OPNsense/Filter
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter reload skip_alias  # noqa no-changed-when
  ansible.builtin.command: configctl filter reload skip_alias
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter refresh_aliases  # noqa no-changed-when
  ansible.builtin.command: configctl filter refresh_aliases
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: reconfig dhcpd service  # noqa no-changed-when
  ansible.builtin.command: /usr/local/sbin/opnsense_service_mimic.php reconfigure_dhcpd
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

- name: restart dhcpd service  # noqa no-changed-when
  ansible.builtin.command: configctl dhcpd restart
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

- name: Restart dns subsystem
  command: pluginctl dns

- name: Restart webgui
  command: configctl webgui restart

- name: Sync filter
  command: configctl filter sync

- name: Reload all services
  command: configctl service reload all

- name: Restart WireGuard
  command: configctl wireguard restart
  when: (lookup("xmlfile", local_config_path_fetch, xpath="opnsense/OPNsense/wireguard") !=
         lookup("xmlfile", local_config_path, xpath="opnsense/OPNsense/wireguard"))

- name: Restart snmpd
  service:
    name: 'snmpd'
    state: 'restarted'
  when: (lookup("xmlfile", local_config_path_fetch, xpath="//opnsense/OPNsense/netsnmp") !=
         lookup("xmlfile", local_config_path, xpath="//opnsense/OPNsense/netsnmp"))
