---

# some configctl infos
# https://docs.opnsense.org/manual/settingsmenu.html

# alias handlers
# see: src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php

# api endpoint /api/firewall/alias/reconfigure

- name: template reload OPNsense/Filter  # noqa no-changed-when
  ansible.builtin.command: configctl template reload OPNsense/Filter
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter reload skip_alias  # noqa no-changed-when
  ansible.builtin.command: configctl filter reload skip_alias
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: filter refresh_aliases  # noqa no-changed-when
  ansible.builtin.command: configctl filter refresh_aliases
  listen:
    - reconfigure aliases
  when:
    - config is defined
    - config.changed | bool

- name: reconfig dhcpd service  # noqa no-changed-when
  ansible.builtin.command: /usr/local/sbin/opnsense_service_mimic.php reconfigure_dhcpd
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

- name: restart dhcpd service  # noqa no-changed-when
  ansible.builtin.command: configctl dhcpd restart
  listen:
    - restart dhcpd
  when:
    - config is defined
    - config.changed | bool

- name: reconfigure vlans  # noqa no-changed-when
  ansible.builtin.command: /usr/local/opnsense/scripts/interfaces/reconfigure_vlans.php
  when:
    - config is defined
    - config.changed | bool

- name: reconfigure laggs  # noqa no-changed-when
  ansible.builtin.command: /usr/local/opnsense/scripts/interfaces/reconfigure_laggs.php
  when:
    - config is defined
    - config.changed | bool
